# Generated by Django 4.0.1 on 2022-02-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='id_dial',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
