# Generated by Django 4.0.1 on 2022-02-01 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_board', '0002_alter_dialogs_id_dial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dialogs',
            unique_together={('u1', 'u2')},
        ),
    ]
