# Generated by Django 4.0.1 on 2022-02-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_board', '0003_alter_dialogs_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='u2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
