# Generated by Django 4.0.1 on 2022-02-02 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_board', '0004_alter_dialogs_u2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='u1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_u1_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialogs',
            name='u2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_u2_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
